### PR TITLE
Remove checkmark with 'x'

### PR DESCRIPTION
**Pull request by Massi-X**
Fix the removal of checkmark when clicking the 'x' button (previously the checkmark was not removed until the dropdown reopen)

### CODE REVIEW

**Comment by yairEO** [comment]
I am not seeing this issue:


https://github.com/user-attachments/assets/5835e0d2-1668-4216-b32f-47fd85109715

**Comment by Massi-X** [comment]
Nope this happens in select mode, anyway I will attach video for this and the others PR (I have one or two still in the works!)

**Comment by Massi-X** [comment]
@yairEO There you go, you can see in the video the bug happening. In select mode the checkmark is not removed + the input lose focus when clicking the 'x' button. This has also the side effect of fixing the dropdown not closing with click outside because the input doesn't have focus (everything is in the video)


https://github.com/user-attachments/assets/b094931c-bc84-42dd-a0e7-5b016ac0c798

**Comment by yairEO** [comment]
Hi, the fix should be that the `x` button should not be visible if the suggestions dropdown is visible (open) - I will do this now

**Comment by Massi-X** [comment]
OK! I don't even use the button myself (hidden in CSS), it was only a thing I noticed.

**Pull request closed without merging**
