### PR TITLE
Added the ability for the dropdown to expand beyond the width of the input

### PR DESCRIPTION
**Pull request by yosefbuskila**
Thank you so much for the amazing library,
You saved us a lot of work.

I want to allow the dropdown to expand beyond the input.
To this day you only allow it if I choose position=text,
But I do want the position to be "all" but the dropdown will still be allowed to expand beyond the input.
For this I added a boolean property called "widthAuto", and made sure in the code to implement it.
I also added a boolean property called "overflowToLeft" for RTL languages (we develop applications in Hebrew) which causes the dropdown to expand to the left.

I also made sure that in this case the border-top of the dropdown would not be canceled.

I created in the test folder 2 examples to implement this:
     users-list-overflow.html
     users-list-overflow-to-left.html

I added the documentation for this to the readme file.

### CODE REVIEW

**Comment by yairEO** [comment]
It is the nature of Taigfy to be easily configured out-of-the-box and as I don't expect Tagify's default look to work for 100% of projects' needs, the CSS is expected to be overwritten, just as the  the case mentioned here can be solved with 3 easy CSS overrides:


https://github.com/yairEO/tagify/assets/845031/7b32b0fd-949e-4421-9daf-782fbe284eae

**Comment by yosefbuskila** [comment]
The ability to control what I offered in PR through CSS is limited.

- I defined min-width in the code so that in any case the dropdown will not be smaller than the size of the input (it's not pretty when it's smaller than the input).
- I develop in Hebrew, so I need the dropdown to slide to the left, and this is only possible if we define "right" instead of "left" in the code.
- I defined "max-width" so that the dropdown does not grow beyond the width that the end of the screen allows.

image

**Comment by yairEO** [comment]
You can create a [jsbin](https://jsbin.com/jekuqap/edit?html,js,output) and show me

BTW - I also speak Hebrew (but please not here because Github is others won't understand)

**Comment by yosefbuskila** [comment]
In both examples I show use of tagify and only change css as your suggested. I change "width" property to "auto".

https://jsbin.com/wejusajuku/1/edit?html,js,output
In this demo I show use of tagify at RTL mode.
the result: the dropdown expend to left, but we need that it will expend to right.

https://jsbin.com/ducosirime/edit?html,js,output
In this demo I show the case that the width of dropdown is smaller of input, I can not set "min-width" as width of input becouse the calculate width of input exists at code only.
so the result is not pretty.

**Comment by yairEO** [comment]
I've just now released a new version with dropdown RTL (positioning) support and also the ability to have a wider dropdown, basically as wide as the widest rendered option

https://yaireo.github.io/tagify/#section-rtl

image

**Comment by yosefbuskila** [comment]
thank you very much.
we used it.
it's very good.

**Pull request closed without merging**
