### PR TITLE
Typescript Declarations

### PR DESCRIPTION
**Pull request by centrual**
I can't find some method declarations in docs. This declaration file can be more clear if we can declare them.

Have a great day!

### CODE REVIEW

**Comment by yairEO** [comment]
What 😲😲😲
I have to maintain all this now?

What is this good for? I don't know or like typescript because I view it a threat to absolutly beautiful languague which I have been coding for over 15 years - Javascript.

Same reason I don't like makeup on women - I prefer things natural, they way they were created.

**Comment by yairEO** [comment]
I see many parameters for methods are missing, why?

Also, I **LOVE** multi-typed function-arguments (love love...so much loving), so a parameter may be of many types, (mostly `String`/`Array`/`Object`) and the function itself is capable of understanding how should it behave accordingly, so many methods may recieve multiple types for some or the arguments (I reserve this rule for the first argument. other ones are mostly single-type)

Does this file handles multiple-types for parameters?

**Comment by Attrash-Islam** [comment]
This is for autocomplete in VSCode

**Comment by Attrash-Islam** [comment]
See the GIF in this PR I opened in fiverr/passable to get an idea -> https://github.com/fiverr/passable/pull/106

**Comment by sakethsaxena** [comment]
Any ETA on when this will be merged?

**Comment by yairEO** [comment]
I am reluctant to merge this for two reasons:

1. it will inflate the package's size (people judge packages by this parameter)
2. I would have to constantly maintain this file as Tagify evolves. It is a manual-time-consuming labour and if forgotten, I don't see how is it possible to know what was forgotten exactly (say, after a month) since there are so so many declarations 
3. *Typescript* is not mainstream, so most developers won't benefit from this extra (constant) work

**Comment by hugomn** [comment]
+1 for needing the typescript type definitions. If the package creator doesn't want to merge, can we create it at DefinitelyTyped at least? Thanks!

**Comment by kurtinaitis** [comment]
Who can push it to DefinitelyTyped?

**Comment by yairEO** [comment]
@centrual - could you make a PR for this in [`DefinitelyTyped`](https://github.com/DefinitelyTyped/DefinitelyTyped#how-can-i-contribute) like others have suggested in this discussion?

https://github.com/DefinitelyTyped/DefinitelyTyped#how-can-i-contribute

**Comment by jpbberry** [comment]
Any progress on this? Without any type declaration the package essentially becomes useless in typescript.

**Comment by jpbberry** [comment]
I'd even think that something like would benefit from being coded directly in typescript, you should try it out @yairEO 
It would 100% be beneficial to compatibility and could possible cut down on unpacked size too, you wouldn't need a lot of the polyfills etc, and would handle the single file compiling for you and provide the declaration files, meaning you wouldn't need to maintain one big file of typings and rather you just need to write you code with types and all will work beautifully.

**Comment by yairEO** [comment]
@jpbberry - why is it useless? it's a third-party script like countless others on the internet. A project based on typescript can easily integrate it. it's not "useless".

I am just being lazy. As I said in my previous comment, somebody should take initiative and contribute declarations to:

DefinitelyTyped/DefinitelyTyped#how-can-i-contribute

I just don't want to bother myself with any typescript and keeping it up to date.
I am flooded with other open-source projects I want to advance with, and wish to invest minimum time on Tagify, as it is very stable and working well.

**Comment by jpbberry** [comment]
That's fine I guess I'll wait for 3rd party types.

I called it useless because of the way typescript in itself works. I get absolutely no codesense and especially with a mundane addition like this one that's only gonna be used one or two times.
I have to memorize every single method and what they do, and what parameters they take and a project like this where you're not mainstream and don't have built in codesense makes it extremely difficult to use in anything that isn't a browser console that automatically runs through all the properties, which is just not what it should be like.

I'll probably just ended up building something myself but types would make the biggest difference imo.
@yairEO

**Comment by yairEO** [comment]
@jpbberry - what exactly do you need to memorize? how is this different from any other API of a third-party script you must "memorize" when importing to a project? You cannot possibly re-build yourself countless third-party scripts which some took years to create, just so you could have autocomplete in your IDE...

simply go to the README of third-party code and read the docs when you need to work with it, which is probably not a thing anyone would do on a daily basis. Once you set up Tagify, it's pretty much done I would say, and it's not that hard..there are already many examples in the demo page for many of the possible scenarios, so I don't understand why would you want to waste months of your time re-build a tags component, only to have typescript declarations...

**Comment by yairEO** [comment]
Anyway, the file in the pull requests is for React for some reason, and I would prefer it not to mention React at all, since this library is not necessarily for React

**Comment by jpbberry** [comment]
I don't disagree with the react part, I wasn't planning on using it for react, however importing the library with something like webpack should be supported, there's no reason not to.
Typescript begins to remove codesense when using an interop module like this one, for example in js
image
in typescript
image
typescript would be the exact thing to be supported if this package were to exist on npm at all, else why wouldn't someone just use a CDN and <script> a js file, it seems useless to support node packages, unless you're using typescript, something that's all too commonly built and webpacked be it react or many other custom implementations.

I will say my initial reaction saying the package was useless was a little harsh so I am sorry for that, it just sucks to be left with no support for the language I use and many others would use this package for.
@yairEO

**Comment by gravitymedianet** [comment]
> I can't find some method declarations in docs. This declaration file can be more clear if we can declare them.
> 
> Have a great day!

@centrual  Can you please provide some comments on how to implement this?

**Comment by Brakebein** [comment]
> I am just being lazy. As I said in my previous comment, somebody should take initiative and contribute declarations to:
> 
> DefinitelyTyped/DefinitelyTyped#how-can-i-contribute

I already made some type declarations as part of my Angular wrapper ([ngx-tagify](https://github.com/Brakebein/ngx-tagify)). So, I thought I can contribute them to DefinitelyTyped. I spent some time on working out how things are done (it's my first DT contribution), updating and completing the declarations (looking at both code and readme docs), and writing a test file (required by DT). Now, it's in the pipeline ([see pull request](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/50895)) and will hopefully be available soon.

**Comment by yairEO** [comment]
BTW, you can simply import *Tagify* and get rid of all the annoying *typescript* issues:

https://github.com/microsoft/TypeScript/issues/3019#issuecomment-355516799

**Comment by Brakebein** [comment]
Now, the type declarations are online (be aware of the 2 underscores):

    npm install --save-dev @types/yaireo__tagify

I also exposed two interfaces `TagData` and `TagifySettings`.

```typescript
// use interfaces this way
import Tagify from '@yaireo/tagify';

const settings: Tagify.TagifySettings = { delimiter: ',' };
const tags: Tagify.TagData[] = [{ value: 'hello' }, { value: 'world', class: 'red' }];

// or this way
import Tagify, { TagData, TagifySettings } from '@yaireo/tagify';

const settings: TagifySettings = { delimiter: ',' };
const tags: TagData[] = [{ value: 'hello' }, { value: 'world', class: 'red' }];

// ----
const tagify: Tagify = new Tagify(inputEl, settings);
tagify.addTags(tags);
```

I will try to keep the declarations up to date, if something changes in this library. But everybody is welcome to contribute.

TypeScript users might be happy now, as well as pure JavaScript users who want to use autocomplete in their IDE. Happy coding!

**Pull request closed without merging**
