### PR TITLE
Fix suggestions when using select all

### PR DESCRIPTION
**Pull request by Massi-X**
Hi @yairEO this should be my last PR, take your time to review and/or improve them and ask me if you need any clarifications!

To trigger this bug (mode is select with whitelist):
1. Select a value
2. Close the dropdown
3. Tab into the input
4. Select all (ctrl+A/cmd+A)
5. Write something (the beginning of another value)
6. No suggestion shows up

I think this happens because the focus is not on the input but rather on the `tagText` element, fixed the behavior by adding another case to `onWindowKeyDown` handler that calls the `onInput` handler.

https://github.com/user-attachments/assets/43e10ea6-b3e1-4b3e-87e4-739c9494a40c

### CODE REVIEW

**Comment by yairEO** [comment]
Hi, I've carefully investigated this bug and had made a fix which is very different than yours.
This requires very deep knowledge in Tagify's code which only I possess :)

**Comment by Massi-X** [comment]
No problem, you're great thanks!

**Comment by yairEO** [comment]
@Massi-X - How do you keep your Tagify package updated (NPM) if you are manually patching it?

**Comment by Massi-X** [comment]
It's embedded, I'm not using NPM!

**Comment by yairEO** [comment]
OK but still, how to you manage to merge the my updates with your changes... it seems like a very delicate work which can get frustrating

**Comment by Massi-X** [comment]
Yep indeed I'm waiting for all the fixes to be implemented 😅

**Pull request closed without merging**
