### PR TITLE
added backspaceDelete to configuration to enable/disable the use of b…

### PR DESCRIPTION
**Pull request by ramiweiss**
…ackspace key to delete tag

### CODE REVIEW

**Comment by ramiweiss** [comment]
Fixed XSS vulnerability

**Comment by ramiweiss** [comment]
@yairEO

**Comment by yairEO** [comment]
sorry I was on vacation, am looking into this now

**Comment by yairEO** [comment]
irrelevant since I re-wrote more or less the whole code of this project

But thank you!

See new docts with the new setting

**Pull request closed without merging**
