### PR TITLE
add tagSanitizer setting

### PR DESCRIPTION
**Pull request by jake**
This adds a setting to transform/sanitize the users input before validating/adding.

I need this because my backend transforms the tags once they are received, and I want the preview the user enters to reflect what will be done on the backend once they submit their post.

### CODE REVIEW

**Comment by yairEO** [comment]
Technically you could have done this using the custom event listener `add` : 

## Example:

    tagify.on('add', function(e){
        if( e.detail.value == 'xxx' ){
            tagify.removeTag.call(tagify, e.detail.tag, false, false);
            tagify.addTags(e.detail.value + '!!!');
        }
    });

the above will transform the `xxx` input into `xxx!!!`

**Comment by jake** [comment]
hmm, that doesn't seem to work. `e.detail.tag` is an empty hash in the add callback using your code sample.

either way, isn't it more clear to allow process on the input before adding the tag than removing and re-adding it?

**Comment by yairEO** [comment]
Yeah, there was a bug in the `add` custom event which prevent the tag element from being sent to the `add` callback, but I've fixed this in the latest version you you first need to up update.

**Comment by yairEO** [comment]
The reason I'm reluctant to add this is because I don't want to bloat Tagify too much, with too many settings, which might confuse users or make it appear to some that this script is too much for their needs, which it counter-productive to the reasons I've made it, which were to have a simple, very lightweight script for tags, because all the others were very bloated and seemed like an overkill for most cases

**Comment by jake** [comment]
I understand and appreciate that. It is one of the reasons I picked it over all the others, so good job and thank you!

I would argue that a mechanism for transforming the input on the way into the system is simple enough, and offers enough capability to be worth adding. The system is a more complete loop: you can transform input on the way in, validate the input against a pattern, and observe events after all that passes. Conflating "transformation" with "events after" is the most confusing approach IMO.

**Comment by yairEO** [comment]
Alright, I'm convinced, I will add support for a transformation function

**Pull request closed without merging**
