### PR TITLE
:sparkle: added angular support

### PR DESCRIPTION
**Pull request by LironHazan**

### CODE REVIEW

**Comment by yairEO** [comment]
Cool!
Are you sure we need the `.idea` folder in this PR? isn't it specific to your computer?

**Comment by LironHazan** [comment]
@yairEO no need for .idea files :) I didn't ignored them at first - removed!

**Comment by yairEO** [comment]
What is the `/angular/src/app` directory is for?

https://github.com/LironHazan/tagify/tree/master/angular/src/app

**Comment by LironHazan** [comment]
@yairEO the src/app is the example-app I used for the readme example (and I used it for tests) we don't really need it, but it won't be bundled anyway, the /dist is generated out of the tagify-module-wrapper only

**Comment by yairEO** [comment]
Thanks @LironHazan !

**Comment by yairEO** [comment]
Github now warns me that the _Angular_ package is using dangerous modules:

image

**Comment by LironHazan** [comment]
I'll checkout I aim to reduce redundant dependencies - the project was generated by using angular-cli

**Pull request merged**
