### PR TITLE
Added vuejs support

### LINKED ISSUE #257: Add support for vuejs
Please add support for vuejs.

### PR DESCRIPTION
**Pull request by haseebeqx**
closes #257

### CODE REVIEW

**Comment by haseebeqx** [comment]
This PR adds vue js support

inside vue component 
```js
components: {
  tagify
},
data(){
  return {
    tagifySettings: {callbacks:{
        add: this.onAddTag,
        remove: this.onRemoveTag
      }
    }
}
```
template:

```html
<template>
  <tagify :settings="tagifySettings" placeholder="tags" name="tags"></tagify>
</template>
```

**Comment by haseebeqx** [comment]
@yairEO I added the support for vuejs. Should I add documentation as codepen ? or as markdown in readme?

**Comment by yairEO** [comment]
The React wrapper is quite large and exposes all the events and so on. This wrapper is nothing like the React. I feel this is wrong.

**Comment by haseebeqx** [comment]
@yairEO Things are quite simple in the Vue world 😄 . I will create a codepen.

**Comment by haseebeqx** [comment]
@yairEO  https://codesandbox.io/s/tagify-vue-vg7k0
Please let me know if anything needs to be added.

**Comment by AdrienTo** [comment]
@haseebeqx Thanks a lot for this vue component, it solved a bug I had using the raw tagify library with vuestic, it didn't applied to the proper input element (I guess the `this.$el` in the declaration did the trick).

If I may add a suggestion,  it would be great that if you v-bind the settings, any change applied to settings in the parent component would update the settings in the tagify component. I needed this feature to update the tag whitelist and it did not work natively. I guess you can do it with a [watcher](https://vuejs.org/v2/guide/computed.html#Watchers) on the settings property (don't forget the ['deep'](https://vuejs.org/v2/api/#watch) option) and update the settings in a similar fashion to the [React component](https://github.com/yairEO/tagify/blob/master/dist/react.tagify.js).

To follow up the @yairEO comment, don't you think that binding each tagify event to a [vuejs custom event](https://vuejs.org/v2/guide/components-custom-events.html) would be more in the vue framework spirit? Your solution with callbacks in the codeopen is perfectly fine, but I think it would not be hard to code this feature and would make the vue component more powerful.

Thanks again for this component and if you don't have time to implement this feature, I am ready to give a try.

**Comment by yairEO** [comment]
10x! I will add documentaion myself

**Comment by haseebeqx** [comment]
@AdrienTo Thanks 
 you can put a ref and get `tagify` instance directly from it.
```html
<tagify ref="tagifyInstance" :settings="tagifySettings" ></tagify>
```

and latter you can access `tagify` instance by using
```js
this.$refs.tagifyInstance.tagify
```

So, in that way it will become 100% functional.

**Pull request merged**
